### ISSUE TITLE
Support multiple deployments per project

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/terraform-dynamic-python-webapp#45]
Current blocking resources (possibly incomplete): 

  * Firebase
    * `google_firebase_project` is a singleton per project. 
    * Workaround: (potentially) `firebase_hosting_site` (investigation needed)
  * Post Deployment resources
    * `gce-vpc`, `subnet_name`, and `google_compute_instance` names are currently static
    * Fix: add `random_suffix` logic to both

**Comment by NimJay** [comment]
* @glasnt thanks for creating this issue (for visibility).
* I believe the `google_firebase_project` singleton issue is now fixed in [`terraform-provider-google-beta` releases `v4.60.0`](https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.60.0) — see pull-request [`terraform-provider-google-beta/pull/5379`](https://github.com/hashicorp/terraform-provider-google-beta/pull/5379).

**Comment by glasnt** [comment]
@NimJay The fix in https://github.com/hashicorp/terraform-provider-google-beta/pull/5379 relates to using and reusing google_firebase_project on one project; it's still a singleton on the project (you can only have one). To allow multiple deployments, I need to work out how to use firebase_hosting_site. 

I should have noted this earlier: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebase_hosting_site is in beta, and may have other Error 409/reuse issues.
