### ISSUE TITLE
Feature Request: Surface Purchase Mode as a terraform variable

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/terraform-dynamic-python-webapp#48]
Currently the implementation of purchase mode is based on directing to a different client image. This is a manual process based on implementation details that aren't particular visible. 

Feature: add `-var purchase_mode` (default: "default", "") that will configure the client image location. 

Still keep client/server image overrides for more granular deployments (particularly for custom image testing)

**Comment by grayside** [comment]
It would be great to have some test coverage that the client image which is published to serverless-ecommerce registry is "cart mode" and that the serving app is also cart mode. That way if something goes wrong along the many hand-offs of these settings we have some checkpoints. Adding this here because it feels like something that should be done in tandem with a new mode, but this could also be a separate cleanup issue.

**Comment by glasnt** [comment]
Cloud Labels allow key-value tagging, but image tagging are just keys. 

Changing the terraform to accept a `version` and a `purchase_mode` flag, then using a concatenation of that to identify the image tag (e.g `v1.7.0-buynow`, `v1.4.1-cart`) would allow for identification of elements. 

Backwards compat around allowing for overriding of image locations, etc, to be considered.

**Comment by glasnt** [comment]
This would be a nice to have, and if any application is going to do this sort of feature flag, the flag should be at the TF level for CFT/JSS usability. But it's out of scope now. Closing.
